# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Azure subscription 1 (a377fdf1-74fd-41e9-9fca-fc0409212b3a)'
#     appType: 'apiApp'
#     WebAppName: 'JDCCommanderAPI'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (a377fdf1-74fd-41e9-9fca-fc0409212b3a)'
    appType: 'apiApp'
    WebAppName: 'JDCCommanderAPI'
    deployToSlotOrASE: true
    ResourceGroupName: 'JDCCommanderResourceGroup'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
